# Generated by Django 4.2.1 on 2023-05-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_xsegmentationresult_pathdeteksitepicanny_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ximage',
            old_name='date',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='xsegmentationresult',
            old_name='date',
            new_name='dateCreated',
        ),
        migrations.AddField(
            model_name='ximage',
            name='contrastEnhancement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ximage',
            name='dateModified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ximage',
            name='edgeDetection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ximage',
            name='exposureCorrection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ximage',
            name='nameImage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ximage',
            name='noiseReduction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ximage',
            name='normalization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ximage',
            name='scaleRatio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ximage',
            name='smoothing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xsegmentationresult',
            name='dateModified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
