# Generated by Django 4.2.1 on 2023-05-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_ximage_edgedetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='ximage',
            name='backgroundDominant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
