# Generated by Django 4.2.1 on 2023-05-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_ximage_backgrounddominant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ximage',
            name='sizeImage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
