# Generated by Django 4.2.1 on 2023-05-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_ximage_sizeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ximage',
            old_name='exposureCorrection',
            new_name='distanceObject',
        ),
        migrations.RemoveField(
            model_name='ximage',
            name='normalization',
        ),
        migrations.RemoveField(
            model_name='ximage',
            name='smoothing',
        ),
    ]
