# Generated by Django 4.2.1 on 2023-05-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_xsegmentationresult_pathpreprocessing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xsegmentationresult',
            name='pathDeteksiTepiCanny',
        ),
        migrations.RemoveField(
            model_name='xsegmentationresult',
            name='pathDeteksiTepiPrewitt',
        ),
        migrations.RemoveField(
            model_name='xsegmentationresult',
            name='pathDeteksiTepiSobel',
        ),
        migrations.RemoveField(
            model_name='xsegmentationresult',
            name='pathGroundTruth',
        ),
        migrations.RemoveField(
            model_name='xsegmentationresult',
            name='pathSegmentationAdaptive',
        ),
        migrations.RemoveField(
            model_name='xsegmentationresult',
            name='pathSegmentationKMeans',
        ),
        migrations.RemoveField(
            model_name='xsegmentationresult',
            name='pathSegmentationOtsu',
        ),
        migrations.AddField(
            model_name='xsegmentationresult',
            name='pathSegmentationResult',
            field=models.JSONField(null=True),
        ),
    ]
